### ISSUE TITLE
Step 1

### ISSUE THREAD

**Issue by wicoop** [z-shell/zsh-virtual-jet#6]
Based on: https://github.com/z-shell/zsh-docker-jet/pull/4/files

It seems that we want to ensure we have docker and docker-compose installed before anything else. Is this true?

**Comment by 0xMRTT** [comment]
Yes 👌

**Comment by 0xMRTT** [comment]
True 👍

**Comment by 0xMRTT** [comment]
Zsh jet

**Comment by ss-o** [comment]
zsh-virt-jet or zsh-virtual-jet? To have a reference in a name?

**Comment by 0xMRTT** [comment]
Zsh-virtual-jet

**Comment by 0xMRTT** [comment]
you mean with code or comment ?

**Comment by 0xMRTT** [comment]
added :+1:
